### ISSUE TITLE
How can you convert the CSS Props values into pixel values?

### ISSUE THREAD

**Issue by 2ne** [scroll-out/scroll-out#22]
The current values work well for scaling and fading as they are 0-1 but I was looking to blur an image based on its viewport X value so I would like to go from filter: blur(0) - filter: blur(10px)

**Comment by notoriousb1t** [comment]
Something like this should work for filter:

```css
.my-class {
    filter: blur(
        calc(10px * var(--viewport-x));
    );
}
```

If you need to do something like 5px to 10px, you could adapt that as such:

```css
.my-class {
    filter: blur(
        calc(5px + calc(5px * var(--viewport-x)));
    );
}
```
