### ISSUE TITLE
Add feature to detect if element scroll in from bottom and scrolling out at the top

### ISSUE THREAD

**Issue by leph83** [scroll-out/scroll-out#30]
I want Elements to scroll in from the bottom with translateY(10%) but when they reach the top I want them to translate to -10%. Couldn't figure how to do it with the current version. Would love to have that feature.

**Comment by notoriousb1t** [comment]
You should be able to do something like this to achieve that affect:

```css
[data-scroll="in"] {
  transition: transform 350ms;
  transform: translateY(calc(10% * var(--intersect-y)));
}
```
Let me know if that works for your project. 😄
