### ISSUE TITLE
Different animation every 2nd section

### ISSUE THREAD

**Issue by jesper9610** [scroll-out/scroll-out#36]
So right now the reveal animation makes a section slide in from the left. But how would i make it so every 2nd section slides in from the right side?
Can't seem to find anything about it in the documentation

**Comment by notoriousb1t** [comment]
If the sections are siblings, you can provide an alternate transition by adding a different transition using :nth-child(2n).

```css
[data-scroll] {
  transition: transform 350ms;
}
[data-scroll="in"] {
  transform: translateX(0);
}
[data-scroll="out"]:nth-child(2n-1) {
  /* odd */
  transform: translateX(100%);
}
[data-scroll="out"]:nth-child(2n) {
  /* even */
  transition: translateX(-100%);
}
```

Alternatively, if you are dealing with non-siblings and static content, you can assign an "alt" class to each second section and then target it separately through css:

```css
[data-scroll] {
  transition: transform 350ms;
}
[data-scroll="in"] {
  transform: translateX(0);
}
[data-scroll="out"]{
  /* odd */
  transform: translateX(100%);
}
[data-scroll="out"].alt {
  /* even */
  transition: translateX(-100%);
}
```
